### ISSUE TITLE
feature request: specify branch

### ISSUE THREAD

**Issue by maltegrosse** [wilvk/githubdl#12]
Hello,

is there any way to specify the branch from where I want to download an entire folder? 
I only found the "entire branch download" option.

**Comment by wilvk** [comment]
hi there,

you should be able to do this by specifying both a [branch](https://github.com/wilvk/githubdl#references) and a [directory](https://github.com/wilvk/githubdl#entire-directory) in the same command.

e.g.

```
githubdl -u ... -d ... -r ...
```

See [here](https://github.com/wilvk/githubdl#entire-directory-from-a-specific-commit) for an example with a commit SHA. A commit SHA is replaceable with a branch name as a reference.

HTH.
