### ISSUE TITLE
Exception: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by AlfredoZuloaga** [wilvk/githubdl#4]
When use file by file I don't get any problem but when I tried to download a directory a got this

- Requesting file: spring-cloud-data-flow/batch-job\src at url: https://api.github.com/repos/eugenp/tutorials/contents/spring-cloud-data-flow/batch-job\src
2018-11-08 09:47:50,083 - root         - CRITICAL - Unable to retrieve list of files from response.
 Exception: 'str' object has no attribute 'get'
 Response: {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}

The command was
githubdl -u "https://github.com/eugenp/tutorials.git" -d "spring-cloud-data-flow/"

also tried
 githubdl -u "https://github.com/eugenp/tutorials.git" -d "spring-cloud-data-flow/" -t "."

**Comment by wilvk** [comment]
Works for me.. sorry. What OS are you running the first command on? And Python version?

**Comment by wilvk** [comment]
The backslash at the end of the url in the error message suggests you may be on Windows. As it hasn't been tested on Windows yet, I've created an issue to track this #5 .

Thanks for the report.
